server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小，默认1MB
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true #显示ip而不是计算机名字
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #提取本机的ip
ly:
  oss:
    host: http://image.leyou.com # 访问oss的域名，很重要bucket + endpoint    代理http://leyoumall1.oss-cn-beijing.aliyuncs.com
    endpoint: oss-cn-beijing.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: "" # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M
