server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///leyou?characterEncoding=UTF-8
    username: root
    password: root
#myBatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
  #mapper-locations: classpath*:mapper/**Mapper.xml #该项目不会出现xml文件，可以注释
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 #间隔多久去拉取服务注册信息，默认为30秒
  instance:
    prefer-ip-address: true #显示ip而不是计算机名字
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #提取本机的ip
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: ${spring.application.name} #相当于是item-service